---

- name: Set up cactus
  gather_facts: yes
  become: true
  hosts: cactus
  vars_files:
    - vars/vault_west.yml
  vars:
    ansible_command: "ansible-playbook --vault-password-file /home/vlad/ops/vault_pass.txt -i /home/vlad/ops/ansible/cactus_hosts /home/vlad/ops/ansible/main.yml"
    timezone: "{{ vault.timezone }}"
    iscsi:
      server: "{{ vault.iscsi.server }}"
      mount_device: "/dev/disk/by-label/iscsi-data"
    certbot:
      renew_command: "certbot renew --dns-cloudflare-propagation-seconds 30"
    plex:
      claim_code: "{{ vault.plex.claim_code }}"
    ddns:
      cloudflare_api_key: "{{ vault.ddns.cloudflare_api_key }}"
      zone: "{{ vault.ddns.zone }}"
      subdomain: "{{ vault.ddns.subdomain }}"
    pihole:
      query_logging: "false"
      password: "{{ vault.pihole.password }}"
      hostname: "{{ vault.pihole.hostname }}"
    haproxy:
      tls_dir: "{{ vault.haproxy.tls_dir }}"
    services_docker_network: "services"
  roles:
    - docker
    - home
    - downloaders
    - plex
    - router
  pre_tasks:
  - name: Connect to the only available iSCSI target on the NAS
    open_iscsi:
      portal: '{{ iscsi.server }}'
      discover: yes
      show_nodes: yes
      login: yes
      automatic: yes
    notify:
      - Mount data
  - name: Run Ansible hourly
    cron: 
      name: "Run Ansible hourly"
      special_time: hourly
      job: "{{ ansible_command }}"
    become: no
  - name: Run Ansible at boot
    cron: 
      name: "Run Ansible at boot"
      special_time: reboot
      job: "{{ ansible_command }}"
    become: no
  handlers:
  - name: Mount data
    mount:
      path: /data
      src: '{{ iscsi.mount_device }}'
      fstype: xfs
      state: mounted
      opts: 'inode64,_netdev'

- name: Set up klaxon
  gather_facts: yes
  become: true
  hosts: klaxon
  vars_files:
    - vars/vault_east.yml
  vars:
    ansible_command: "ansible-playbook --vault-password-file /home/vlad/ops/vault_pass.txt -i /home/vlad/ops/ansible/klaxon_hosts /home/vlad/ops/ansible/main.yml"
    timezone: "{{ vault.timezone }}"
    certbot:
      renew_command: "certbot renew --dns-cloudflare-propagation-seconds 30"
    plex:
      claim_code: "{{ vault.plex.claim_code }}"
    ddns:
      cloudflare_api_key: "{{ vault.ddns.cloudflare_api_key }}"
      zone: "{{ vault.ddns.zone }}"
      subdomain: "{{ vault.ddns.subdomain }}"
    pihole:
      query_logging: "false"
      password: "{{ vault.pihole.password }}"
      hostname: "{{ vault.pihole.hostname }}"
    haproxy:
      tls_dir: "{{ vault.haproxy.tls_dir }}"
    services_docker_network: "services"
  roles:
    - docker
    - downloaders
    - plex
    - router
  pre_tasks:
  - name: Ensure /data exists locally
    file:
      path: /data
      state: directory
  - name: Run Ansible hourly
    cron: 
      name: "Run Ansible hourly"
      special_time: hourly
      job: "{{ ansible_command }}"
    become: no
  - name: Run Ansible at boot
    cron: 
      name: "Run Ansible at boot"
      special_time: reboot
      job: "{{ ansible_command }}"
    become: no
