---

- name: Pre-task
  gather_facts: yes
  become: true
  hosts: all, localhost
  connection: local
  tasks:
    - name: Add host to correct group
      group_by:
        key: "{{ ansible_hostname }}"

- name: Set up cactus
  gather_facts: yes
  become: true
  hosts: cactus
  vars_files:
    - vars/vault_west.yml
  vars:
    timezone: "{{ vault.timezone }}"
    iscsi:
      server: "{{ vault.iscsi.server }}"
      target: "{{ vault.iscsi.target }}"
      mount_device: "/dev/disk/by-label/iscsi-data"
    certbot:
      renew_command: "certbot renew --dns-cloudflare-propagation-seconds 30"
    betterstack:
      token: "{{ vault.betterstack.token }}"
    plex:
      claim_code: "{{ vault.plex.claim_code }}"
    ddns:
      cloudflare_api_key: "{{ vault.ddns.cloudflare_api_key }}"
      zone: "{{ vault.ddns.zone }}"
      subdomain: "{{ vault.ddns.subdomain }}"
    pihole:
      query_logging: "false"
      password: "{{ vault.pihole.password }}"
      hostname: "{{ vault.pihole.hostname }}"
    haproxy:
      tls_dir: "{{ vault.haproxy.tls_dir }}"
    services_docker_network: "services"
    tailscale:
      routes: "{{ vault.tailscale.routes }}"
  roles:
    - core
    - betterstack
    - docker
    - home
    - downloaders
    - plex
    - router
    - tailscale
  pre_tasks:
  - name: Connect to the only available iSCSI target on the NAS
    open_iscsi:
      portal: '{{ iscsi.server }}'
      target: '{{ iscsi.target }}'
      discover: yes
      show_nodes: yes
      login: yes
      auto_node_startup: yes
    notify:
      - Mount data
  handlers:
  - name: Mount data
    mount:
      path: /data
      src: '{{ iscsi.mount_device }}'
      fstype: xfs
      state: mounted
      opts: 'inode64,_netdev'

- name: Set up klaxon
  gather_facts: yes
  become: true
  hosts: klaxon
  vars_files:
    - vars/vault_east.yml
  vars:
    timezone: "{{ vault.timezone }}"
    certbot:
      renew_command: "certbot renew --dns-cloudflare-propagation-seconds 30"
    betterstack:
      token: "{{ vault.betterstack.token }}"
    plex:
      claim_code: "{{ vault.plex.claim_code }}"
    ddns:
      cloudflare_api_key: "{{ vault.ddns.cloudflare_api_key }}"
      zone: "{{ vault.ddns.zone }}"
      subdomain: "{{ vault.ddns.subdomain }}"
    pihole:
      query_logging: "false"
      password: "{{ vault.pihole.password }}"
      hostname: "{{ vault.pihole.hostname }}"
    haproxy:
      tls_dir: "{{ vault.haproxy.tls_dir }}"
    services_docker_network: "services"
    tailscale:
      routes: "{{ vault.tailscale.routes }}"
  roles:
    - core
    - betterstack
    - docker
    - downloaders
    - plex
    - router
    - tailscale
  pre_tasks:
  - name: Ensure /data exists locally
    file:
      path: /data
      state: directory
