---

- name: Create unifi user
  user:
    name: unifi
    create_home: false
    shell: /usr/bin/false
    state: present
  register: unifi_user

- name: Unifi controller container
  docker_container:
    name: unifi-controller
    image: jacobalberty/unifi
    pull: yes
    state: started
    volumes:
      - /data/docker/unifi-controller/data:/unifi/data
      - /data/docker/unifi-controller/log:/unifi/log
      - /data/docker/unifi-controller/run:/var/run/unifi
      - /data/docker/unifi-controller/cert:/unifi/cert
    env:
      UNIFI_UID: "{{ unifi_user.uid }}"
      UNIFI_GID: "{{ unifi_user.group }}"
      TZ: America/Los_Angeles
    ports:
      - "{{ unifi_controller.port.http }}:8080"
      - "{{ unifi_controller.port.https }}:8443"
      - "{{ unifi_controller.port.http_guest_portal }}:8880"
      - "{{ unifi_controller.port.https_guest_portal }}:8843"
      - '6789:6789'
      - '3478:3478/udp'
      - '10001:10001/udp'
