---

- name: Create downloads group
  group:
    name: downloads
    state: present

- name: Create sabnzb user
  user:
    name: sabnzb
    group: downloads
    create_home: false
    shell: /usr/bin/false
    state: present
  register: sabnzb_user

- name: Create sonarr user
  user:
    name: sonarr
    group: downloads
    create_home: false
    shell: /usr/bin/false
    state: present
  register: sonarr_user

- name: Create radarr user
  user:
    name: radarr
    group: downloads
    create_home: false
    shell: /usr/bin/false
    state: present
  register: radarr_user

- name: Create downloaders Docker network
  docker_network:
    name: "{{ downloaders.docker_network }}"
    enable_ipv6: false

- name: Sabnzbd container
  docker_container:
    name: sabnzbd
    image: linuxserver/sabnzbd
    pull: yes
    state: started
    volumes:
      - /data/docker/sabnzbd/config:/config
      - /data/downloads:/data/downloads
    env:
      PUID: "{{ sabnzb_user.uid }}"
      PGID: "{{ sabnzb_user.group }}"
      TZ: "{{ timezone }}"
    networks:
      - name: "{{ downloaders.docker_network }}"

- name: Sonarr container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    pull: yes
    state: started
    volumes:
      - /data/docker/sonarr/config:/config
      - /data/downloads:/data/downloads
      - /data/anime-manual-import:/data/anime-manual-import
      - /data/plex/shows:/data/plex/shows
    env:
      PUID: "{{ sonarr_user.uid }}"
      PGID: "{{ sonarr_user.group }}"
      TZ: "{{ timezone }}"
    networks:
      - name: "{{ downloaders.docker_network }}"
    security_opts:
      - "seccomp=unconfined"

- name: Radarr container
  docker_container:
    name: radarr
    image: linuxserver/radarr
    pull: yes
    state: started
    volumes:
      - /data/docker/radarr/config:/config
      - /data/downloads:/data/downloads
      - /data/plex/movies:/data/plex/movies
    env:
      PUID: "{{ radarr_user.uid }}"
      PGID: "{{ radarr_user.group }}"
      TZ: "{{ timezone }}"
    networks:
      - name: "{{ downloaders.docker_network }}"

- name: Bazarr container
  docker_container:
    name: bazarr
    image: lscr.io/linuxserver/bazarr
    pull: yes
    state: started
    volumes:
      - /data/docker/bazarr/config:/config
      - /data/plex/shows:/data/plex/shows
      - /data/plex/movies:/data/plex/movies
    env:
      PUID: "{{ radarr_user.uid }}"
      PGID: "{{ radarr_user.group }}"
      TZ: "{{ timezone }}"
    networks:
      - name: "{{ downloaders.docker_network }}"

- name: Overseerr container
  docker_container:
    name: overseerr
    image: sctx/overseerr
    pull: yes
    state: started
    volumes:
      - /data/docker/overseerr/config:/app/config
    env:
      PUID: "{{ radarr_user.uid }}"
      PGID: "{{ radarr_user.group }}"
      TZ: "{{ timezone }}"
    networks:
      - name: "{{ downloaders.docker_network }}"

- name: Prowlarr container
  docker_container:
    name: prowlarr
    image: lscr.io/linuxserver/prowlarr
    pull: yes
    state: started
    volumes:
      - /data/docker/prowlarr/config:/config
    env:
      PUID: "{{ radarr_user.uid }}"
      PGID: "{{ radarr_user.group }}"
      TZ: "{{ timezone }}"
    networks:
      - name: "{{ downloaders.docker_network }}"

- name: Create Sabnzbd dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sabnzb_user.uid }}"
    group: "{{ sabnzb_user.group }}"
    mode: 0775
  loop:
    - /data/downloads/complete-sab
    - /data/downloads/incomplete-sab
    - /data/downloads/nbz-files

- name: Create Sonarr dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sonarr_user.uid }}"
    group: "{{ sonarr_user.group }}"
    mode: 0775
  loop:
    - /data/downloads/tv
    - /data/plex/shows

- name: Create Radarr dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ radarr_user.uid }}"
    group: "{{ radarr_user.group }}"
    mode: 0775
  loop:
    - /data/downloads/movies
    - /data/plex/movies
