ddns:
  cloudflare_api_key: XXXXXXXXXXXXXXX
  zone: example.com
  subdomain: test

haproxy:
  tls_dir: /etc/letsencrypt/live/example.com
  docker_networks:
    - name: "bridge"
    - name: "{{ services_docker_network }}"
    - name: "{{ downloaders.docker_network }}"
    - name: "{{ plex.docker_network }}"

certbot:
  renew_command: "certbot renew"

pihole:
  hostname: pi.hole
  upstream_dns: "1.1.1.1;8.8.8.8"
  password: ""
