ddns:
  cloudflare_api_key: XXXXXXXXXXXXXXX
  zone: example.com
  subdomain: test

haproxy:
  tls_dir: /etc/letsencrypt/live/example.com

certbot:
  renew_command: "certbot renew"

pihole:
  port: 8001
  hostname: pi.hole
  upstream_dns: "1.1.1.1;8.8.8.8"
  password: ""
