---

- name: Create services Docker network
  docker_network:
    name: "{{ services_docker_network }}"
    enable_ipv6: false

- name: PiHole container
  docker_container:
    name: pihole
    image: pihole/pihole
    pull: yes
    state: started
    volumes:
      - /data/docker/pihole/etc/pihole:/etc/pihole
      - /data/docker/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    env:
      TZ: America/Los_Angeles
      PIHOLE_DNS_: "{{ pihole.upstream_dns }}"
      DNS_BOGUS_PRIV: "true"
      TEMPERATUREUNIT: f
      DNSMASQ_USER: pihole
      WEBPASSWORD: "{{ pihole.password }}"
      VIRTUAL_HOST: "{{ pihole.hostname }}"
    dns_servers:
      - 1.1.1.1
    networks:
      - name: "{{ services_docker_network }}"
    ports:
      - "53:53"
      - "53:53/udp"
