---

- name: Install Docker repo prereqs
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: latest

# Install the correct repo per distro
- include_tasks: "{{ ansible_distribution }}.yml"

- name: Install Docker engine
  package:
    name:
      - docker-ce
      - docker-ce-cli
    state: latest

- name: Install Docker Python libs
  package:
    name:
      - python3-docker
#      - docker-compose

- name: Cleanup Docker cruft
  community.docker.docker_prune:
    containers: true
    images: true
    builder_cache: true
