---

- name: Create downloads group
  group:
    name: downloads
    state: present

- name: Create plex user
  user:
    name: plex
    append: true
    groups:
      - downloads
      - video
    create_home: false
    shell: /usr/bin/false
    state: present
  register: plex_user

- name: Create Plex Docker network
  docker_network:
    name: "{{ plex.docker_network }}"
    enable_ipv6: false

- name: Plex container
  docker_container:
    name: plex
    image: plexinc/pms-docker
    pull: yes
    state: started
    volumes:
      - /data/docker/plex/config:/config
      - /data/downloads:/data/downloads
      - /data/plex:/data/plex
    env:
      PLEX_UID: "{{ plex_user.uid }}"
      PLEX_GID: "{{ plex_user.group }}"
      TZ: "{{ timezone }}"
      ADVERTISE_IP: "{{ plex.advertise_ip }}"
      PLEX_CLAIM: "{{ plex.claim_code }}"
    devices:
     - "/dev/dri:/dev/dri"
    networks:
      - name: "{{ plex.docker_network }}"
    ports:
      - "{{ plex.port }}:32400"